version: 1.0.0.{build}

image: Visual Studio 2019

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# build cache to preserve files/folders between builds
cache:
  - packages

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore

build:
  parallel: true                # enable MSBuild parallel builds
  project: SharpUV.sln          # path to Visual Studio solution or project
  publish_nuget: true           # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false  # generate and publish NuGet symbol packages

test:

# here we are going to override common configuration
for:

# override settings for `stable` branch
-
  branches:
    only:
      - stable

  configuration: Release

  deploy:
    provider: NuGet
    api_key:
      secure: t5VmoPZFy/8eIv4i5yyLuHQ9cVvrGTsAgV4olTuWi5RPiu2UOb1LAgA0aTQMNnEq
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/
